# Generated by Django 5.0.1 on 2024-02-13 08:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('store', '0004_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.RESTRICT, to='store.product'),
        ),
    ]
