# Generated by Django 5.0 on 2023-12-20 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bonhomieapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='category',
            new_name='Category',
        ),
    ]
