# Generated by Django 5.0 on 2023-12-21 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bonhomieapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_name',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
