# Generated by Django 5.0 on 2023-12-20 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bonhomieapp', '0003_rename_category_products_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='featuered',
            new_name='featured',
        ),
    ]
